bounty-effect:
  enabled: true
  material: CHEST
physical-rewards:
  enabled: false
  list:
    GOLD_NUGGET: 10
    INK_SACK: 4 1
auto-bounty: false
auto-bounty-reward: 100
drop-head: false
new-hunter-alert: true
disable-compass: false
compass-price: 1000
min-reward: 0
max-reward: 0
tax: 15
round-distance: false
display-death-quote-on-title: false
hide-bounty-when-no-perm: false
gui-up-bounty: false
gui-up-bounty-percent: 20
world-blacklist:
  - INSERT_WORLD_HERE