name: BountyHunters
version: 1.3
main: me.Indyuce.bh.Main
author: Indyuce
softdepend: [Vault]
commands:
  bounties:
    description: See all the active bounties.
  addbounty:
    description: Create a bounty on a player.
    aliases: [bounty, setbounty]
permissions:
  bountyhunters.gui:
    default: op
  bountyhunters.leaderboard-gui:
    default: op
  bountyhunters.add:
    default: op
  bountyhunters.claim:
    default: op
  bountyhunters.bypass-imun:
    default: op
  bountyhunters.imun:
    default: op
  bountyhunters.op:
    default: op